-- Find total customers by countries
SELECT
country,
COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;
-- Find total products by category
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
category,
AVG(cost) as AVERAGE_COST
FROM gold.dim_products
GROUP BY category
ORDER BY AVERAGE_COST DESC;

-- What is the total revenue generated for each categroy?
SELECT
dp.category,
SUM(s.sales_amount) as total_revenue
FROM  gold.fact_sales s 
LEFT JOIN gold.dim_products dp
on s.product_key=dp.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;

-- Find total revenure generated by each customer
SELECT
c.customer_id,
c.first_name,
c.last_name,
SUM(s.sales_amount) as total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
on s.customer_key= c.customer_key 
GROUP BY c.customer_id,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;

-- Whats the distribution of sold items across countries?
SELECT
c.country,
SUM(s.quantity) as sold_items
FROM gold.fact_sales s 
LEFT JOIN gold.dim_customers c
ON  s.customer_key=c.customer_key
GROUP BY c.country
ORDER BY sold_items DESC;
